### ISSUE TITLE
Impedance mismatch with `Write` API

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/transceiver-control#9]
The FPGA API uses _broadcast_ write operations, i.e. you fill one buffer, then it writes to every transceiver selected with a bitmask.

The current `transceiver-control` API declares that _multiple_ byte-arrays are stored after the `HostRequest::Write(MemoryRegion)`.

I'd suggest modifying the docstring and having this API to do a broadcast write, to match the FPGA's behavior.

**Comment by bnaecker** [comment]
Closed by #10
